/**
 * Integration tests for the First-Client Lead Capture path
 * (app/api/leads/capture/[token]/route.ts). Mirrors that route's exact
 * sequence - organization resolution by lead_intake_token, resolveOrCreateContact,
 * the recent-lead duplicate-submission guard, lead insert, then
 * emitLeadCreatedFollowupAsService - by calling the real functions the route
 * calls, the same "call the real functions the route calls" technique
 * already established for the inbound SMS webhook (see
 * lib/contacts/inbound-sms-dedup.integration.test.ts). Run with:
 *
 *   node --import ./lib/automation/test-loader.mjs --test lib/leads/capture.integration.test.ts
 */
import { test, before, after } from "node:test";
import assert from "node:assert/strict";
import { createRequire } from "node:module";
import fs from "node:fs";
import path from "node:path";

const REPO_ROOT = process.cwd();
const require = createRequire(path.join(REPO_ROOT, "package.json"));

const envPath = path.join(REPO_ROOT, ".env.local");
if (fs.existsSync(envPath)) {
  for (const line of fs.readFileSync(envPath, "utf8").split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (value.startsWith('"') && value.endsWith('"')) value = value.slice(1, -1);
    if (!(key in process.env)) process.env[key] = value;
  }
}

const { createServiceRoleClient }: typeof import("@/lib/supabase/service") = require(path.join(REPO_ROOT, "lib/supabase/service.ts"));
const { resolveOrCreateContact }: typeof import("@/lib/contacts/resolve") = require(path.join(REPO_ROOT, "lib/contacts/resolve.ts"));
const { emitLeadCreatedFollowupAsService }: typeof import("@/lib/automation/lead-followup") = require(
  path.join(REPO_ROOT, "lib/automation/lead-followup.ts"),
);

const service = createServiceRoleClient();

let organizationId: string;
let otherOrganizationId: string;
let intakeToken: string;

before(async () => {
  const { data: org } = await service.from("organizations").insert({ name: "Lead Capture Integration Test Org" }).select("id, lead_intake_token").single();
  organizationId = org!.id;
  intakeToken = org!.lead_intake_token;
  const { data: other } = await service.from("organizations").insert({ name: "Lead Capture Integration Test Org (Other)" }).select("id").single();
  otherOrganizationId = other!.id;
});

after(async () => {
  await service.from("organizations").delete().eq("id", organizationId); // cascades contacts/leads/conversations/automation_events/workflow_executions
  await service.from("organizations").delete().eq("id", otherOrganizationId);
});

/** Mirrors the route's own token -> organization resolution exactly - never trusts a client-supplied organization id. */
async function resolveOrganizationByToken(token: string): Promise<string | null> {
  const { data } = await service.from("organizations").select("id").eq("lead_intake_token", token).maybeSingle();
  return data?.id ?? null;
}

test("1. a real per-organization token was generated by the migration and is unique", async () => {
  assert.ok(intakeToken, "every organization must have a lead_intake_token");
  assert.equal(intakeToken.length >= 32, true);
});

test("2. token resolves to the correct organization - never a client-supplied id", async () => {
  const resolved = await resolveOrganizationByToken(intakeToken);
  assert.equal(resolved, organizationId);
});

test("3. an unknown token resolves to no organization", async () => {
  const resolved = await resolveOrganizationByToken("not-a-real-token-00000000000000000000");
  assert.equal(resolved, null);
});

test("4. a new phone number creates exactly one contact and one lead, scoped to the resolved organization", async () => {
  const orgId = (await resolveOrganizationByToken(intakeToken))!;
  const contactResult = await resolveOrCreateContact(service, { organizationId: orgId, firstName: "Capture", lastName: "Test", phone: "+15555551001" });
  // node:assert/strict's equal() has a narrowing `asserts` signature, so
  // TypeScript already knows contactResult.outcome is exactly "created"
  // below - no further guard needed (an extra one here actually breaks
  // narrowing, since it would compare an already-literal type against
  // values TS now knows are impossible).
  assert.equal(contactResult.outcome, "created");

  const { data: lead } = await service
    .from("leads")
    .insert({ organization_id: orgId, contact_id: contactResult.contact.id, service: "Roof repair", source: "lead_capture_api", status: "new", temperature: "cold" })
    .select("id, organization_id, contact_id")
    .single();

  assert.equal(lead?.organization_id, organizationId);
  assert.equal(lead?.contact_id, contactResult.contact.id);
});

test("5. the same phone number submitted twice within the duplicate window resolves to the same contact - no second contact created", async () => {
  const orgId = (await resolveOrganizationByToken(intakeToken))!;
  const first = await resolveOrCreateContact(service, { organizationId: orgId, phone: "+15555551002" });
  const second = await resolveOrCreateContact(service, { organizationId: orgId, phone: "+15555551002" });
  assert.equal(first.outcome, "created");
  assert.equal(second.outcome, "matched");
  assert.equal(first.contact.id, second.contact.id);
});

test("6. a lead created moments ago for the same contact is treated as a duplicate submission (the route's own recent-lead guard)", async () => {
  const orgId = (await resolveOrganizationByToken(intakeToken))!;
  const contactResult = await resolveOrCreateContact(service, { organizationId: orgId, phone: "+15555551003" });
  if (contactResult.outcome === "error" || contactResult.outcome === "conflict") throw new Error("unexpected");
  const contactId = contactResult.contact.id;

  const { data: firstLead } = await service
    .from("leads")
    .insert({ organization_id: orgId, contact_id: contactId, service: "Estimate request", source: "lead_capture_api", status: "new", temperature: "cold" })
    .select("id")
    .single();

  // Mirrors the route's own duplicate-window query exactly.
  const duplicateWindowStart = new Date(Date.now() - 10 * 60 * 1000).toISOString();
  const { data: recentLead } = await service
    .from("leads")
    .select("id")
    .eq("organization_id", orgId)
    .eq("contact_id", contactId)
    .gte("created_at", duplicateWindowStart)
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  assert.equal(recentLead?.id, firstLead?.id, "a second submission within the window must resolve to the existing lead, not create a new one");
});

test("7. organization isolation: a lead created under one organization's token is never visible when resolving the OTHER organization's token", async () => {
  const orgAId = (await resolveOrganizationByToken(intakeToken))!;
  const contactResult = await resolveOrCreateContact(service, { organizationId: orgAId, phone: "+15555551004" });
  if (contactResult.outcome === "error" || contactResult.outcome === "conflict") throw new Error("unexpected");

  const { data: matchInOtherOrg } = await service
    .from("contacts")
    .select("id")
    .eq("organization_id", otherOrganizationId)
    .eq("phone_normalized", "+15555551004")
    .maybeSingle();

  assert.equal(matchInOtherOrg, null, "a contact created for org A must never be found when querying org B");
});

test("8. emitLeadCreatedFollowupAsService creates a real lead.created automation event, idempotently on replay", async () => {
  const orgId = (await resolveOrganizationByToken(intakeToken))!;
  const contactResult = await resolveOrCreateContact(service, { organizationId: orgId, phone: "+15555551005" });
  if (contactResult.outcome === "error" || contactResult.outcome === "conflict") throw new Error("unexpected");
  const contactId = contactResult.contact.id;

  const { data: lead } = await service
    .from("leads")
    .insert({ organization_id: orgId, contact_id: contactId, service: "Kitchen remodel", source: "lead_capture_api", status: "new", temperature: "cold" })
    .select("id")
    .single();
  const leadId = lead!.id;

  await emitLeadCreatedFollowupAsService(service, {
    leadId,
    contactId,
    organizationId: orgId,
    source: "lead_capture_api",
    service: "Kitchen remodel",
    status: "new",
    temperature: "cold",
    estimatedValue: null,
  });

  const { data: events } = await service.from("automation_events").select("id, event_type, entity_id").eq("organization_id", orgId).eq("entity_id", leadId);
  assert.equal(events?.length, 1);
  assert.equal(events?.[0].event_type, "lead.created");

  // Replay (e.g. a caller retrying the same lead id) must not create a second event.
  await emitLeadCreatedFollowupAsService(service, {
    leadId,
    contactId,
    organizationId: orgId,
    source: "lead_capture_api",
    service: "Kitchen remodel",
    status: "new",
    temperature: "cold",
    estimatedValue: null,
  });
  const { data: eventsAfterReplay } = await service.from("automation_events").select("id").eq("organization_id", orgId).eq("entity_id", leadId);
  assert.equal(eventsAfterReplay?.length, 1, "no duplicate automation event on replay");
});

test("9. a freshly created organization (this test org, via the same path a new signup takes) defaults to Test mode, so the outbound gate blocks any real send from a captured lead until explicitly switched to Live", async () => {
  const { data: org } = await service.from("organizations").select("automation_mode").eq("id", organizationId).single();
  assert.equal(org?.automation_mode, "test");
});
