import type { SupabaseClient } from "@supabase/supabase-js";
import { calendarDateInTimeZone, formatInvoiceNumber, isOverdue } from "@/lib/invoices/domain";
import { canAcceptOnlinePayments } from "./connect";

/**
 * Phase 1C: the service-side logic behind the public app/pay/[token] page.
 *
 * Trust model: identical to lib/estimates/approval.ts. invoices.payment_token
 * is 48 hex characters generated by the database (never by application code
 * or a client - invoices_payment_token_guard), resolved with the service-role
 * client. The token authorizes reading ONE invoice's payment summary and
 * starting a Checkout Session for its balance; it is not a session and grants
 * nothing else.
 *
 * What the customer may see: the business name and phone (the same pair the
 * quote page shows), the invoice number, title, dates and money. Never
 * selected: invoices.notes (internal), void_reason, created_by, the job,
 * contact or estimate. Read here but never returned publicly: the
 * organization's subscription payment_status and Stripe Connect fields -
 * the customer only learns whether online payment is available, never why
 * not. Drafts (never sent) and void invoices resolve to null, so a leaked
 * token for either behaves as if it does not exist.
 */

export const PAYMENT_TOKEN_PATTERN = /^[0-9a-f]{48}$/;

export type PublicInvoiceStatus = "sent" | "partially_paid" | "paid";

export type OnlinePaymentAvailability = { available: true; reason?: undefined } | { available: false; reason: "paid" | "not_accepting_online_payments" };

export type PublicInvoice = {
  label: string;
  title: string;
  status: PublicInvoiceStatus;
  total: number;
  amountPaid: number;
  balanceDue: number;
  issuedAt: string | null;
  dueDate: string | null;
  paidAt: string | null;
  overdue: boolean;
  organizationName: string;
  organizationPhone: string | null;
  onlinePayment: OnlinePaymentAvailability;
};

/** Server-only: everything Checkout Session creation needs. Never render this. */
export type PayableInvoiceRecord = {
  invoiceId: string;
  organizationId: string;
  jobId: string;
  number: number;
  label: string;
  title: string;
  status: PublicInvoiceStatus;
  total: number;
  amountPaid: number;
  balanceDue: number;
  issuedAt: string | null;
  dueDate: string | null;
  paidAt: string | null;
  organizationName: string;
  organizationPhone: string | null;
  organizationTimezone: string;
  organizationPaymentStatus: string | null;
  connectAccountId: string | null;
  connectChargesEnabled: boolean;
};

// Explicit column list - notes, void_reason and the relationships are
// deliberately absent. A single literal for Supabase's select parser.
const PAYABLE_INVOICE_COLUMNS =
  "id, organization_id, job_id, number, status, title, total, amount_paid, balance_due, issued_at, due_date, paid_at, organization:organizations(name, sms_phone_number, timezone, payment_status, stripe_connect_account_id, stripe_connect_charges_enabled)";

type RawOrganization = {
  name: string;
  sms_phone_number: string | null;
  timezone: string | null;
  payment_status: string | null;
  stripe_connect_account_id: string | null;
  stripe_connect_charges_enabled: boolean | null;
};

type RawRow = {
  id: string;
  organization_id: string;
  job_id: string;
  number: number;
  status: string;
  title: string;
  total: number | string;
  amount_paid: number | string;
  balance_due: number | string;
  issued_at: string | null;
  due_date: string | null;
  paid_at: string | null;
  organization: RawOrganization | RawOrganization[] | null;
};

const PUBLIC_STATUSES = new Set<string>(["sent", "partially_paid", "paid"]);

/**
 * Resolves a payment token to the invoice record behind it, or null for an
 * unknown/malformed token, a draft, a void invoice, or a row without its
 * organization. Server-only - see PayableInvoiceRecord.
 */
export async function loadPayableInvoiceByToken(service: SupabaseClient, token: string): Promise<PayableInvoiceRecord | null> {
  if (typeof token !== "string" || !PAYMENT_TOKEN_PATTERN.test(token)) return null;

  const { data, error } = await service.from("invoices").select(PAYABLE_INVOICE_COLUMNS).eq("payment_token", token).maybeSingle();
  if (error || !data) return null;

  const row = data as RawRow;
  if (!PUBLIC_STATUSES.has(row.status)) return null;
  const organization = Array.isArray(row.organization) ? (row.organization[0] ?? null) : row.organization;
  if (!organization) return null;

  return {
    invoiceId: row.id,
    organizationId: row.organization_id,
    jobId: row.job_id,
    number: row.number,
    label: formatInvoiceNumber(row.number),
    title: row.title,
    status: row.status as PublicInvoiceStatus,
    total: Number(row.total),
    amountPaid: Number(row.amount_paid),
    balanceDue: Number(row.balance_due),
    issuedAt: row.issued_at,
    dueDate: row.due_date,
    paidAt: row.paid_at,
    organizationName: organization.name,
    organizationPhone: organization.sms_phone_number,
    organizationTimezone: organization.timezone || "UTC",
    organizationPaymentStatus: organization.payment_status,
    connectAccountId: organization.stripe_connect_account_id,
    connectChargesEnabled: organization.stripe_connect_charges_enabled === true,
  };
}

export function onlinePaymentAvailability(record: Pick<PayableInvoiceRecord, "status" | "balanceDue" | "organizationPaymentStatus" | "connectAccountId" | "connectChargesEnabled">): OnlinePaymentAvailability {
  if (record.status === "paid" || record.balanceDue <= 0) return { available: false, reason: "paid" };
  const eligible = canAcceptOnlinePayments({
    paymentStatus: record.organizationPaymentStatus,
    connect: { accountId: record.connectAccountId, chargesEnabled: record.connectChargesEnabled },
  });
  return eligible ? { available: true } : { available: false, reason: "not_accepting_online_payments" };
}

/** The customer-facing projection: only the fields listed in PublicInvoice, nothing internal. */
export function toPublicInvoice(record: PayableInvoiceRecord, now: Date = new Date()): PublicInvoice {
  const today = calendarDateInTimeZone(now, record.organizationTimezone);
  return {
    label: record.label,
    title: record.title,
    status: record.status,
    total: record.total,
    amountPaid: record.amountPaid,
    balanceDue: record.balanceDue,
    issuedAt: record.issuedAt,
    dueDate: record.dueDate,
    paidAt: record.paidAt,
    overdue: isOverdue({ status: record.status, dueDate: record.dueDate }, today),
    organizationName: record.organizationName,
    organizationPhone: record.organizationPhone,
    onlinePayment: onlinePaymentAvailability(record),
  };
}

export async function getPublicInvoiceByPaymentToken(service: SupabaseClient, token: string, now: Date = new Date()): Promise<PublicInvoice | null> {
  const record = await loadPayableInvoiceByToken(service, token);
  return record ? toPublicInvoice(record, now) : null;
}
