-- Quote Approval Links (V1): a public, tokenized approval surface for sent
-- estimates - the customer-facing half of the estimate lifecycle.
--
-- Why: the estimate follow-up automation (Phase 4.5) texts customers about
-- a quote they cannot actually open anywhere - acceptance today requires
-- either the customer texting an unambiguous "yes" (estimate-reply.ts's
-- conservative classifier) or the contractor marking it accepted by hand.
-- This migration gives every estimate an unguessable public token so a
-- follow-up text can carry a link where the customer sees the quote and
-- approves (or declines) it in one tap. The page/route layer lives in
-- app/quote/[token] and lib/estimates/approval.ts.
--
-- Token model: exactly organizations.lead_intake_token's own pattern
-- (20260916... migration) - 48 hex chars from pgcrypto's gen_random_bytes,
-- generated by the database as a column default, never by application code,
-- unique-indexed for the public lookup. The token authorizes READ of one
-- estimate's summary and a single sent->accepted/declined transition; it is
-- not a session and grants nothing else.
--
-- approval_first_viewed_at: set once, the first time the customer opens the
-- page while the estimate is still 'sent'. Deliberately a single timestamp,
-- not a view counter or event log - its one consumer is follow-up copy and
-- the attention engine ("she opened the quote but hasn't answered" is a
-- materially different situation from "never opened it"), and one timestamp
-- answers that without a new table.
--
-- RLS: no policy changes. The public page and respond route use the
-- service-role client after resolving the token (the exact trust model of
-- app/api/leads/capture/[token]); the contractor-facing app keeps reading
-- estimates through the existing org-scoped policies, which now simply
-- return two more columns.

alter table public.estimates
  add column if not exists approval_token text,
  add column if not exists approval_first_viewed_at timestamp with time zone;

update public.estimates
  set approval_token = encode(gen_random_bytes(24), 'hex')
  where approval_token is null;

alter table public.estimates
  alter column approval_token set default (encode(gen_random_bytes(24), 'hex'));

alter table public.estimates
  alter column approval_token set not null;

create unique index if not exists estimates_approval_token_unique
  on public.estimates (approval_token);
