-- Rollback for supabase/pending/agent_runs.sql.
--
-- agent_runs holds only derived run history (every row can be regenerated by
-- running the agents again), and nothing else references it, so dropping it
-- loses no business data. Turn TRACKPR_AGENT_RUN_PERSISTENCE off first so
-- the console stops writing.

begin;

drop policy if exists agent_runs_insert on public.agent_runs;
drop policy if exists agent_runs_select on public.agent_runs;
drop table if exists public.agent_runs;

commit;
