-- Trackpr Phase 1C - Online Payments: Stripe Connect accounts, invoice
-- payment links, online card payments, reconciliation incidents.
--
-- STATUS: PENDING. Written and validated (supabase/pending/scratch/
-- validate-online-payments.mjs) but NOT applied anywhere. Apply deliberately
-- per supabase/pending/README.md - never via db push - first to the isolated
-- test project trackpr-stripe-test, and to production only with separate,
-- explicit approval. After the ledger entry is read back, move this file to
-- supabase/migrations/<version>_online_payments.sql.
--
-- Phase 1C lets a contractor's customer pay an issued invoice by card through
-- Stripe Checkout, as a direct charge on the contractor's own connected
-- (Standard-style) Stripe account. Trackpr takes no platform fee. The money
-- never touches Trackpr's own Stripe balance, and a customer paying an
-- invoice never touches the contractor's Trackpr subscription payment_status
-- (Phase 1C step 1, lib/billing/subscription-checkout.ts).
--
-- ACCOUNTING BOUNDARY. The existing invoice/payment rules are not relaxed in
-- any way. An online payment is one more customer_payments row, inserted by
-- the Connect webhook with the service-role client; customer_payments_guard_
-- insert still locks the invoice, still rejects overpayment and payments on a
-- non-issued invoice, and customer_payments_apply is still the only thing
-- that moves invoices.amount_paid / status / paid_at. None of those three
-- functions, invoices_guard_update, or any policy or grant is replaced here.
-- When the database refuses to record money Stripe has already collected,
-- the webhook must raise an 'online_payment_reconciliation' incident (section
-- 4) - never bend a rule to make the insert succeed.
--
-- Four additive, rerun-safe sections:
--
-- 1. organizations: the contractor's Stripe Connect account id and the three
--    capability flags Stripe reports for it (charges_enabled,
--    payouts_enabled, details_submitted), plus when Trackpr last synced them.
--    Identifiers, not secrets - same exposure as stripe_customer_id. Written
--    only by the service role (Connect onboarding return route and the
--    account.updated webhook), enforced by a guard trigger in the exact shape
--    of guard_organizations_stripe_identifiers, extended to INSERT as well:
--    organizations has no INSERT policy today, but the guard should not
--    depend on that staying true.
--
-- 2. invoices.payment_token: the unguessable public token behind the
--    customer-facing app/pay/[token] page - estimates.approval_token's model
--    exactly (48 hex characters from pgcrypto, generated by the database,
--    unique-indexed). ADD COLUMN with a volatile default fills every
--    existing row with its own token during the table rewrite WITHOUT firing
--    row triggers, so invoices_guard_update (which rejects any update to a
--    void invoice) and invoices_updated_at are never involved in the
--    backfill. A separate guard trigger makes the token database-owned: on
--    INSERT it is always regenerated (a client can never choose its own
--    token), and it may only change afterwards through the service role (a
--    future "rotate link" action). The token authorizes reading one
--    invoice's public summary and starting a Checkout Session for its
--    balance; nothing else.
--
-- 3. customer_payments: online card payments.
--    - method gains 'card_online'. The existing manual methods are unchanged;
--      lib/invoices keeps offering only those in the Record payment dialog.
--    - stripe_checkout_session_id, stripe_payment_intent_id, stripe_account_id
--      record exactly which Stripe payment a row represents, so it can always
--      be reconciled against the contractor's Stripe dashboard.
--    - customer_payments_stripe_fields: an ordinary card_online row carries
--      all three; every other row (manual methods, and reversal rows, which
--      copy the original's method) carries none.
--    - Global partial UNIQUE indexes on the checkout session id and on the
--      payment intent id: a replayed or duplicated checkout.session.completed
--      can never create a second row for the same Stripe payment - the
--      second insert fails with 23505 and the webhook resolves it as the
--      already-recorded payment. Global, not per organization: Stripe ids are
--      globally unique, so the same session can never legitimately appear
--      twice anywhere.
--    - customer_payments_online_guard (BEFORE INSERT, a new function; the
--      existing insert guard is untouched): an ordinary card_online row may
--      only be inserted by the service role, and its stripe_account_id must
--      equal the organization's stored stripe_connect_account_id - the
--      database itself verifies the connected account a payment came from.
--      Postgres fires BEFORE triggers in name order, so it runs after
--      customer_payments_guard_insert has locked the invoice and copied the
--      original method onto a reversal row. Reversal rows of a card_online
--      payment go through the existing reversal rules unchanged (Phase 1C's
--      application layer does not offer them yet; refunds are made in the
--      contractor's Stripe dashboard).
--    - customer_payments_immutable is re-created with the three new columns
--      added to the list an UPDATE may never change. It is the only existing
--      invoice/payment function whose body changes.
--
-- 4. Automation incidents: one new category, online_payment_reconciliation,
--    for every case where Stripe and Trackpr's ledger disagree and a person
--    must reconcile by hand: a successful Stripe payment the database refused
--    to record (overpayment, invoice no longer payable, account mismatch), a
--    refund or dispute made in the Stripe dashboard. The reason and the Stripe
--    identifiers travel in metadata. Widening follows 20260924110000 and
--    20260926000000 exactly: the category CHECK, and the allowlist inside
--    record_automation_incident_signal, re-created from its current body
--    (supabase/pending/reference/record_automation_incident_signal.captured.sql,
--    md5 dfca7377dd707f2cd7814f87ae84a6bf) with exactly that one value added.
--    Service-role calls already skip the membership and payment-active
--    checks, so an incident is recorded even for a suspended organization.
--
-- Nothing else changes: no RLS policy, no grant, no existing trigger
-- definition, no other function. New columns inherit the existing table
-- grants (anon still has no access to invoices or customer_payments).
--
-- Idempotent: every statement is add-if-not-exists / create-or-replace /
-- drop-if-exists-then-create, so re-running it is a no-op. Re-running it never
-- drops data.

begin;

-- ---------------------------------------------------------------------------
-- 1. organizations: Stripe Connect account
-- ---------------------------------------------------------------------------

alter table public.organizations
  add column if not exists stripe_connect_account_id text,
  add column if not exists stripe_connect_charges_enabled boolean not null default false,
  add column if not exists stripe_connect_payouts_enabled boolean not null default false,
  add column if not exists stripe_connect_details_submitted boolean not null default false,
  add column if not exists stripe_connect_synced_at timestamp with time zone;

do $$ begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.organizations'::regclass
      and conname = 'organizations_stripe_connect_account_id_shape'
  ) then
    alter table public.organizations
      add constraint organizations_stripe_connect_account_id_shape
      check (stripe_connect_account_id is null or stripe_connect_account_id ~ '^acct_[A-Za-z0-9]{1,255}$');
  end if;
end $$;

-- One connected account belongs to exactly one organization.
create unique index if not exists organizations_stripe_connect_account_id_key
  on public.organizations (stripe_connect_account_id)
  where stripe_connect_account_id is not null;

create or replace function public.guard_organizations_stripe_connect()
returns trigger
language plpgsql
security definer
set search_path = 'public'
as $$
begin
  if auth.role() is not distinct from 'service_role' then
    return new;
  end if;

  if tg_op = 'INSERT' then
    if new.stripe_connect_account_id is not null
       or new.stripe_connect_charges_enabled
       or new.stripe_connect_payouts_enabled
       or new.stripe_connect_details_submitted
       or new.stripe_connect_synced_at is not null then
      raise exception 'Stripe Connect fields can only be set by a trusted server-side process';
    end if;
    return new;
  end if;

  if new.stripe_connect_account_id is distinct from old.stripe_connect_account_id
     or new.stripe_connect_charges_enabled is distinct from old.stripe_connect_charges_enabled
     or new.stripe_connect_payouts_enabled is distinct from old.stripe_connect_payouts_enabled
     or new.stripe_connect_details_submitted is distinct from old.stripe_connect_details_submitted
     or new.stripe_connect_synced_at is distinct from old.stripe_connect_synced_at then
    raise exception 'Stripe Connect fields can only be changed by a trusted server-side process';
  end if;
  return new;
end;
$$;

drop trigger if exists organizations_stripe_connect_guard on public.organizations;
create trigger organizations_stripe_connect_guard
  before insert or update on public.organizations
  for each row
  execute function public.guard_organizations_stripe_connect();

-- ---------------------------------------------------------------------------
-- 2. invoices.payment_token
-- ---------------------------------------------------------------------------

-- The volatile default is evaluated once per existing row during the rewrite
-- (no row triggers fire), so every existing invoice gets its own token.
alter table public.invoices
  add column if not exists payment_token text not null default encode(extensions.gen_random_bytes(24), 'hex');

do $$ begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.invoices'::regclass
      and conname = 'invoices_payment_token_shape'
  ) then
    alter table public.invoices
      add constraint invoices_payment_token_shape
      check (payment_token ~ '^[0-9a-f]{48}$');
  end if;
end $$;

create unique index if not exists invoices_payment_token_unique
  on public.invoices (payment_token);

create or replace function public.invoices_payment_token_guard()
returns trigger
language plpgsql
security definer
set search_path = 'public'
as $$
begin
  if tg_op = 'INSERT' then
    -- Always database-generated; whatever the client sent is discarded.
    new.payment_token := encode(extensions.gen_random_bytes(24), 'hex');
    return new;
  end if;

  if new.payment_token is distinct from old.payment_token and auth.role() is distinct from 'service_role' then
    raise exception 'payment_token can only be changed by a trusted server-side process';
  end if;
  return new;
end;
$$;

drop trigger if exists invoices_payment_token_guard on public.invoices;
create trigger invoices_payment_token_guard
  before insert or update on public.invoices
  for each row
  execute function public.invoices_payment_token_guard();

-- ---------------------------------------------------------------------------
-- 3. customer_payments: online card payments
-- ---------------------------------------------------------------------------

alter table public.customer_payments
  add column if not exists stripe_checkout_session_id text,
  add column if not exists stripe_payment_intent_id text,
  add column if not exists stripe_account_id text;

alter table public.customer_payments
  drop constraint if exists customer_payments_method_check;

alter table public.customer_payments
  add constraint customer_payments_method_check
  check (method in ('cash', 'check', 'card_elsewhere', 'bank_transfer', 'other', 'card_online'));

do $$ begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.customer_payments'::regclass
      and conname = 'customer_payments_stripe_fields'
  ) then
    -- coalesce(..., false): a NULL id makes `~` yield NULL, and a CHECK
    -- treats NULL as passing - a card_online row missing an id must fail.
    alter table public.customer_payments
      add constraint customer_payments_stripe_fields
      check (coalesce(
        case
          when method = 'card_online' and reverses_payment_id is null then
            stripe_checkout_session_id ~ '^cs_(test|live)_[A-Za-z0-9]{1,255}$'
            and stripe_payment_intent_id ~ '^pi_[A-Za-z0-9]{1,255}$'
            and stripe_account_id ~ '^acct_[A-Za-z0-9]{1,255}$'
          else
            stripe_checkout_session_id is null
            and stripe_payment_intent_id is null
            and stripe_account_id is null
        end,
        false
      ));
  end if;
end $$;

-- A Stripe payment is recorded at most once, anywhere.
create unique index if not exists customer_payments_stripe_checkout_session_unique
  on public.customer_payments (stripe_checkout_session_id)
  where stripe_checkout_session_id is not null;

create unique index if not exists customer_payments_stripe_payment_intent_unique
  on public.customer_payments (stripe_payment_intent_id)
  where stripe_payment_intent_id is not null;

create or replace function public.customer_payments_online_guard()
returns trigger
language plpgsql
security definer
set search_path = 'public'
as $$
declare
  v_connected_account text;
begin
  -- Manual methods and reversal rows are governed entirely by the existing
  -- rules (customer_payments_guard_insert has already run: it fires first,
  -- by name).
  if new.method <> 'card_online' or new.reverses_payment_id is not null then
    return new;
  end if;

  if auth.role() is distinct from 'service_role' then
    raise exception 'Online card payments can only be recorded by the Stripe webhook';
  end if;

  select stripe_connect_account_id into v_connected_account
    from public.organizations where id = new.organization_id;
  if v_connected_account is null or new.stripe_account_id is distinct from v_connected_account then
    raise exception 'stripe_account_id does not match the organization''s connected Stripe account';
  end if;

  return new;
end;
$$;

drop trigger if exists customer_payments_online_guard on public.customer_payments;
create trigger customer_payments_online_guard
  before insert on public.customer_payments
  for each row execute function public.customer_payments_online_guard();

-- 3b. customer_payments_immutable: identical to 20260928181837's body except
--     for the three added Stripe comparisons. The trigger itself is untouched
--     (same name, timing and events); CREATE OR REPLACE swaps the body in
--     place.
create or replace function public.customer_payments_immutable()
returns trigger
language plpgsql
security definer
set search_path = 'public'
as $$
begin
  if tg_op = 'DELETE' then
    raise exception 'customer_payments are append-only; record a reversal instead of deleting';
  end if;

  if new.id <> old.id
     or new.organization_id <> old.organization_id
     or new.invoice_id <> old.invoice_id
     or new.job_id <> old.job_id
     or new.amount <> old.amount
     or new.method <> old.method
     or new.reference is distinct from old.reference
     or new.received_at <> old.received_at
     or new.reverses_payment_id is distinct from old.reverses_payment_id
     or new.recorded_by is distinct from old.recorded_by
     or new.notes is distinct from old.notes
     or new.client_key is distinct from old.client_key
     or new.stripe_checkout_session_id is distinct from old.stripe_checkout_session_id
     or new.stripe_payment_intent_id is distinct from old.stripe_payment_intent_id
     or new.stripe_account_id is distinct from old.stripe_account_id
     or new.created_at <> old.created_at then
    raise exception 'customer_payments are append-only; record a reversal instead of editing';
  end if;

  if new.contact_id is distinct from old.contact_id then
    if new.contact_id is null or not exists (
      select 1 from public.contacts where id = new.contact_id and organization_id = new.organization_id
    ) then
      raise exception 'contact_id must belong to the same organization_id';
    end if;
  end if;

  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- 4. automation incidents: online_payment_reconciliation
-- ---------------------------------------------------------------------------

alter table public.automation_incidents
  drop constraint if exists automation_incidents_category_check;

alter table public.automation_incidents
  add constraint automation_incidents_category_check check (category in (
    'workflow_failed', 'repeated_workflow_failure', 'workflow_stuck',
    'n8n_dispatch_failed', 'n8n_callback_failed',
    'sms_send_failed', 'sms_delivery_failed',
    'human_escalation_requested',
    'scheduled_automation_stale',
    'online_payment_reconciliation'
  ));

-- The captured body, with 'online_payment_reconciliation' added to the
-- allowlist and nothing else changed.
CREATE OR REPLACE FUNCTION public.record_automation_incident_signal(p_organization_id uuid, p_category text, p_severity text, p_fingerprint text, p_title text, p_description text DEFAULT NULL::text, p_automation_id text DEFAULT NULL::text, p_workflow_execution_id uuid DEFAULT NULL::uuid, p_metadata jsonb DEFAULT '{}'::jsonb)
 RETURNS automation_incidents
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_is_service_role boolean;
  v_category text;
  v_severity text;
  v_fingerprint text;
  v_title text;
  v_description text;
  v_automation_id text;
  v_metadata jsonb;
  v_row public.automation_incidents;
begin
  v_is_service_role := (auth.role() = 'service_role');

  if p_organization_id is null then
    raise exception 'organization_id is required';
  end if;

  if not v_is_service_role then
    if auth.uid() is null then
      raise exception 'Not authenticated';
    end if;
    if not public.is_org_member(p_organization_id) then
      raise exception 'Not authorized';
    end if;
    if not public.organization_payment_active(p_organization_id) then
      raise exception 'Organization payment is not active';
    end if;
  end if;

  v_category := nullif(trim(p_category), '');
  if v_category is null or v_category not in (
    'workflow_failed', 'workflow_stuck',
    'n8n_dispatch_failed', 'n8n_callback_failed',
    'sms_send_failed', 'sms_delivery_failed',
    'human_escalation_requested',
    'scheduled_automation_stale',
    'online_payment_reconciliation'
  ) then
    raise exception 'Unsupported incident category';
  end if;

  v_severity := nullif(trim(p_severity), '');
  if v_severity is null or v_severity not in ('info', 'warning', 'critical') then
    raise exception 'Unsupported incident severity';
  end if;

  v_fingerprint := nullif(trim(p_fingerprint), '');
  if v_fingerprint is null or length(v_fingerprint) > 300 then
    raise exception 'Invalid fingerprint';
  end if;

  v_title := nullif(trim(p_title), '');
  if v_title is null or length(v_title) > 200 then
    raise exception 'Invalid title';
  end if;

  v_description := nullif(trim(p_description), '');
  if v_description is not null then
    v_description := left(v_description, 1000);
  end if;

  v_automation_id := nullif(trim(p_automation_id), '');

  v_metadata := coalesce(p_metadata, '{}'::jsonb);
  if jsonb_typeof(v_metadata) is distinct from 'object' then
    raise exception 'metadata must be a JSON object';
  end if;

  insert into public.automation_incidents as ai (
    organization_id, automation_id, workflow_execution_id, category, severity, status,
    fingerprint, title, description, metadata
  ) values (
    p_organization_id, v_automation_id, p_workflow_execution_id, v_category, v_severity, 'open',
    v_fingerprint, v_title, v_description, v_metadata
  )
  on conflict (organization_id, fingerprint) where status in ('open', 'acknowledged')
  do update set
    occurrence_count = ai.occurrence_count + 1,
    last_seen_at = now(),
    workflow_execution_id = coalesce(excluded.workflow_execution_id, ai.workflow_execution_id),
    title = excluded.title,
    description = excluded.description,
    metadata = excluded.metadata,
    updated_at = now(),
    category = case
      when ai.category = 'workflow_failed' and ai.occurrence_count + 1 >= 3 then 'repeated_workflow_failure'
      else ai.category
    end,
    severity = case
      when ai.category = 'workflow_failed' and ai.occurrence_count + 1 >= 3 then 'critical'
      else ai.severity
    end
  returning * into v_row;

  return v_row;
end;
$function$;

-- Same privileges every prior re-creation re-asserted (CREATE OR REPLACE
-- keeps them; restated so the intended state is explicit).
revoke all on function public.record_automation_incident_signal(uuid, text, text, text, text, text, text, uuid, jsonb) from public;
revoke all on function public.record_automation_incident_signal(uuid, text, text, text, text, text, text, uuid, jsonb) from anon;
grant execute on function public.record_automation_incident_signal(uuid, text, text, text, text, text, text, uuid, jsonb) to authenticated, service_role;

commit;
